[package]
name = "iyes_progress"
version = "0.3.0"
edition = "2021"
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/IyesGames/iyes_progress"
keywords = ["game", "gamedev", "bevy"]
categories = ["game-engines"]
description = "Bevy plugin to help implement loading states"

[dependencies]
bevy_ecs = "0.7"
bevy_app = "0.7"
bevy_asset = { version = "0.7", optional = true }
bevy_utils = { version = "0.7", optional = true }

[dependencies.iyes_loopless]
git = "https://github.com/NiklasEi/iyes_loopless"
branch = "loopless-schedule-ext-trait"
optional = true
default-features = false
features = ["states", "app"]

[features]
assets = ["bevy_asset", "bevy_utils"]

[dev-dependencies]
bevy = "0.7"
iyes_loopless = { git = "https://github.com/NiklasEi/iyes_loopless", branch = "loopless-schedule-ext-trait" }
# iyes_loopless = {path = "../iyes_loopless/"}

[[example]]
name = "full"
required-features = ["iyes_loopless", "assets"]
